### ISSUE TITLE
deleting a deployed chart hangs

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#546]
# Description

# Location

- [ ] Browser
- [ ] CLI
- [x] API

# Steps to reproduce

1. Delete an existing chart
2. The dashboard will hang on the deletion loading screen.

# Additional Details
error from the backend:
```
porter_1       | 2021/04/20 02:54:16 /porter/internal/repository/gorm/release.go:31 record not found
porter_1       | [5.544ms] [rows:0] SELECT * FROM "releases" WHERE cluster_id = 3 AND name = 'porter-host' AND namespace = 'default' AND "releases"."deleted_at" IS NULL ORDER BY "releases"."id" LIMIT 1
porter_1       | 2021/04/20 02:54:16 http: panic serving 172.18.0.3:57866: runtime error: invalid memory address or nil pointer dereference
porter_1       | goroutine 13206 [running]:
porter_1       | net/http.(*conn).serve.func1(0xc002a0a280)
porter_1       |        /usr/local/go/src/net/http/server.go:1801 +0x147
porter_1       | panic(0x2324640, 0x38d5b00)
porter_1       |        /usr/local/go/src/runtime/panic.go:975 +0x47a
porter_1       | github.com/porter-dev/porter/server/api.(*App).HandleUninstallTemplate(0xc00074e480, 0x2a00cc0, 0xc000c660c0, 0xc000380b00)
porter_1       |        /porter/server/api/deploy_handler.go:217 +0x3e8
porter_1       | net/http.HandlerFunc.ServeHTTP(0xc0009d6b90, 0x2a00cc0, 0xc000c660c0, 0xc000380b00)
porter_1       |        /usr/local/go/src/net/http/server.go:2042 +0x44
porter_1       | github.com/porter-dev/porter/server/requestlog.(*Handler).ServeHTTP(0xc0009ee2c0, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /porter/server/requestlog/handler.go:49 +0x338
porter_1       | github.com/porter-dev/porter/server/router/middleware.(*Auth).DoesUserHaveClusterAccess.func1(0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /porter/server/router/middleware/auth.go:283 +0x12b
porter_1       | net/http.HandlerFunc.ServeHTTP(0xc0009db410, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /usr/local/go/src/net/http/server.go:2042 +0x44
porter_1       | github.com/porter-dev/porter/server/router/middleware.(*Auth).DoesUserHaveProjectAccess.func1(0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /porter/server/router/middleware/auth.go:225 +0x311
porter_1       | net/http.HandlerFunc.ServeHTTP(0xc0009eac00, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /usr/local/go/src/net/http/server.go:2042 +0x44
porter_1       | github.com/go-chi/chi.(*Mux).routeHTTP(0xc000a677a0, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
porter_1       | net/http.HandlerFunc.ServeHTTP(0xc000a8c1c0, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /usr/local/go/src/net/http/server.go:2042 +0x44
porter_1       | github.com/porter-dev/porter/server/router/middleware.ContentTypeJSON.func1(0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /porter/server/router/middleware/json.go:9 +0x131
porter_1       | net/http.HandlerFunc.ServeHTTP(0xc000a80980, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /usr/local/go/src/net/http/server.go:2042 +0x44
porter_1       | github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000a677a0, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
porter_1       | github.com/go-chi/chi.(*Mux).Mount.func1(0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
porter_1       | net/http.HandlerFunc.ServeHTTP(0xc0009eeb60, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /usr/local/go/src/net/http/server.go:2042 +0x44
porter_1       | github.com/go-chi/chi.(*Mux).routeHTTP(0xc000a67740, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
porter_1       | net/http.HandlerFunc.ServeHTTP(0xc0009d6e50, 0x2a0ef80, 0xc0004121c0, 0xc000380a00)
porter_1       |        /usr/local/go/src/net/http/server.go:2042 +0x44
porter_1       | github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000a67740, 0x2a0ef80, 0xc0004121c0, 0xc000380900)
porter_1       |        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2d1
porter_1       | net/http.serverHandler.ServeHTTP(0xc0009fc000, 0x2a0ef80, 0xc0004121c0, 0xc000380900)
porter_1       |        /usr/local/go/src/net/http/server.go:2843 +0xa3
porter_1       | net/http.(*conn).serve(0xc002a0a280, 0x2a1a080, 0xc00228e400)
porter_1       |        /usr/local/go/src/net/http/server.go:1925 +0x8ad
porter_1       | created by net/http.(*Server).Serve
porter_1       |        /usr/local/go/src/net/http/server.go:2969 +0x36c
```

**Comment by abelanger5** [comment]
Seems to be resolved, case was that release was deployed on one hosted version of Porter, and deleted on a different host. This should no longer throw an error.
